version: '3.8'

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data


  youtube-fetcher:
    build: .
    volumes:
      - ./app:/youtube-fetcher/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    restart: on-failure


